<a href="https://colab.research.google.com/github/LadonV/Data-Viz/blob/main/Quiz_18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ladon Vance

In [3]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/Data_Sets/IOT-temp.csv')

df.head()

,id,room_id/id,noted_date,temp,out/in
0,__export__.temp_log_196134_bd201015,Room Admin,08-12-2018 09:30,29,In
1,__export__.temp_log_196131_7bca51bc,Room Admin,08-12-2018 09:30,29,In
2,__export__.temp_log_196127_522915e3,Room Admin,08-12-2018 09:29,41,Out
3,__export__.temp_log_196128_be0919cf,Room Admin,08-12-2018 09:29,41,Out
4,__export__.temp_log_196126_d30b72fb,Room Admin,08-12-2018 09:29,31,In

In [4]:
df['noted_date'] = pd.to_datetime(df['noted_date'], format='%d-%m-%Y %H:%M')
df.head()

,id,room_id/id,noted_date,temp,out/in
0,__export__.temp_log_196134_bd201015,Room Admin,2018-12-08 09:30:00,29,In
1,__export__.temp_log_196131_7bca51bc,Room Admin,2018-12-08 09:30:00,29,In
2,__export__.temp_log_196127_522915e3,Room Admin,2018-12-08 09:29:00,41,Out
3,__export__.temp_log_196128_be0919cf,Room Admin,2018-12-08 09:29:00,41,Out
4,__export__.temp_log_196126_d30b72fb,Room Admin,2018-12-08 09:29:00,31,In

In [5]:
min_date = df['noted_date'].min()
max_date = df['noted_date'].max()

print(f"Minimum Date and Time: {min_date}")
print(f"Maximum Date and Time: {max_date}")

Minimum Date and Time: 2018-07-28 07:06:00
Maximum Date and Time: 2018-12-08 09:30:00

In [6]:
df_sorted = df.sort_values(by='noted_date')
df_sorted['time_diff'] = df_sorted['noted_date'].diff()

largest_interval = df_sorted['time_diff'].max()

print(f"The largest interval between temperature checks is: {largest_interval}")

The largest interval between temperature checks is: 11 days 13:38:00

In [11]:
df['noted_date_timestamp'] = df['noted_date'].astype('int64') // 10**9

mean_timestamp = df['noted_date_timestamp'].mean()

average_datetime = pd.to_datetime(mean_timestamp, unit='s')

print(f"The average datetime is: {average_datetime}")

The average datetime is: 2018-10-07 05:10:38.821178913

Average datetime

In [10]:
df['noted_date'].median()

Timestamp('2018-10-17 05:10:00')

Median datetime

In [12]:
specific_date = pd.to_datetime('09-11-2018', format='%d-%m-%Y')
outside_temp_on_date = df[(df['noted_date'].dt.date == specific_date.date()) & (df['out/in'] == 'Out')]

if not outside_temp_on_date.empty:
    average_outside_temp = outside_temp_on_date['temp'].mean()
    print(f"The average outside temperature on {specific_date.strftime('%d-%m-%Y')} was: {average_outside_temp:.2f} degrees")
else:
    print(f"No outside temperature data available for {specific_date.strftime('%d-%m-%Y')}")

No outside temperature data available for 09-11-2018

The day 09-11-2018 does not exist in the dataset.